-----
### 네트워크 예외1 - 연결 예외
-----
1. 네트워크 연결 시 발생할 수 있는 예외
```java
package network.tcp.exception.connect;

import java.io.IOException;
import java.net.ConnectException;
import java.net.Socket;
import java.net.UnknownHostException;

public class ConnectMain {
    public static void main(String[] args) throws IOException {
        unknownHostEx1();
        unknownHostEx2();
        connectionRefused();
    }

    private static void unknownHostEx1() throws IOException {
        try {
            Socket socket = new Socket("999.999.999.999", 80); // IP 대역 오류
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
    }
    private static void unknownHostEx2() throws IOException {
        try {
            Socket socket = new Socket("google.gogo", 80); // 도메인 이름 오류
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
    }

    private static void connectionRefused() throws IOException {
        try {
            Socket socket = new Socket("localhost", 45678); // 연결 오류
        } catch (ConnectException e) {
            e.printStackTrace();
        }
    }
}
```
```
java.net.UnknownHostException: 999.999.999.999
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/java.net.Socket.connect(Socket.java:686)
	at java.base/java.net.Socket.<init>(Socket.java:555)
	at java.base/java.net.Socket.<init>(Socket.java:324)
	at network.tcp.exception.connect.ConnectMain.unknownHostEx1(ConnectMain.java:17)
	at network.tcp.exception.connect.ConnectMain.main(ConnectMain.java:10)
java.net.UnknownHostException: google.gogo
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/java.net.Socket.connect(Socket.java:686)
	at java.base/java.net.Socket.<init>(Socket.java:555)
	at java.base/java.net.Socket.<init>(Socket.java:324)
	at network.tcp.exception.connect.ConnectMain.unknownHostEx2(ConnectMain.java:24)
	at network.tcp.exception.connect.ConnectMain.main(ConnectMain.java:11)
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:578)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/java.net.Socket.connect(Socket.java:686)
	at java.base/java.net.Socket.<init>(Socket.java:555)
	at java.base/java.net.Socket.<init>(Socket.java:324)
	at network.tcp.exception.connect.ConnectMain.connectionRefused(ConnectMain.java:32)
	at network.tcp.exception.connect.ConnectMain.main(ConnectMain.java:12)
```

2. java.net.UnknownHostException
   - 호스트를 알 수 없음
   - 999.999.999.999 : 존재하지 않는 IP
   - google.gogo : 존재하지 않는 도메인 이름

3. java.net.ConnectException: Connection refused
   - Connection refused : 연결이 거절되었다는 메세지
   - 연결이 거절 되었다는 것 : 우선 네트워크를 통해 해당 IP의 서버 컴퓨터에 접속은 완료
   - 하지만, 해당 서버 컴퓨터에서 45678 포트를 사용하지 않기 때문에 TCP 연결 거절
   - IP에 해당하는 서버는 켜져있으나, 사용하는 PORT가 없을 때 주로 발생
   - 네트워크 방화벽 등에서 무단 연결로 인지하고 연결을 막을 때도 발생
   - 서버 컴퓨터 OS는 이 때 TCP RST(Rest)라는 패킷을 보내 연결 거절
   - 클라이언트가 연결 시도 중 RST 패킷을 받으면 이 예외 발생

   - 윈도우 OS의 경우 ```java.net.ConnectException: Connection refused```뒤에 connect라는 메세지가 하나 더 붙음
     + ```java.net.ConnectException: Connection refused: connect```

  4. TCP RST(Reset) 패킷 : TCP 연결에 문제가 있다는 뜻으로, 이 패킷을 받으면 받은 대상은 바로 연결을 해제해야 함
